name: Walkie
options:
  bundleIdPrefix: com.jonstuebe
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: 5.9
    TARGETED_DEVICE_FAMILY: 1
    DEVELOPMENT_TEAM: 5US3HNY357

targets:
  Walkie:
    type: application
    platform: iOS
    sources:
      - path: Walkie
    info:
      path: Walkie/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: ""
        NSHealthShareUsageDescription: "Walkie reads your step count to keep your koala fed and happy."
        NSHealthUpdateUsageDescription: "Walkie needs access to your step data."
        UIBackgroundModes:
          - healthkit
        UNUserNotificationCenterDelegate: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconName: AppIcon
          CFBundleAlternateIcons:
            AppIcon-Brown:
              CFBundleIconName: AppIcon-Brown
              UIPrerenderedIcon: false
            AppIcon-Lavender:
              CFBundleIconName: AppIcon-Lavender
              UIPrerenderedIcon: false
            AppIcon-Mint:
              CFBundleIconName: AppIcon-Mint
              UIPrerenderedIcon: false
            AppIcon-Peach:
              CFBundleIconName: AppIcon-Peach
              UIPrerenderedIcon: false
            AppIcon-Slate:
              CFBundleIconName: AppIcon-Slate
              UIPrerenderedIcon: false
            AppIcon-Sand:
              CFBundleIconName: AppIcon-Sand
              UIPrerenderedIcon: false
            AppIcon-Pink:
              CFBundleIconName: AppIcon-Pink
              UIPrerenderedIcon: false
    entitlements:
      path: Walkie/Walkie.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access:
          - health-records
        com.apple.developer.healthkit.background-delivery: true
    dependencies:
      - sdk: HealthKit.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jonstuebe.petwalkie
        INFOPLIST_FILE: Walkie/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
